baseurl = "http://lenkiefer.com/"
title = "Len Kiefer"
theme = "ghostwriter-len"
languageCode = "en-us"
copyright = "Len Kiefer"
#disqusShortname = "XXX"
# google analytics tracking id
googleAnalytics = "UA-66905937-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Author]
    name = "Len Kiefer"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"
    category = "categories"

[Params]
    intro = true
    headline = "Len Kiefer"
    description = "Helping people understand the economy, housing and mortgage markets"
    #github = "https://github.com/XXX"
    linkedin = "https://www.linkedin.com/in/leonard-kiefer-51175331"
    twitter = "https://twitter.com/lenkiefer"
    email = "lenkiefer@hotmail.com"
    opengraph = false
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""


[Permalinks]
    post = "/:year/:month/:day/:slug/"
    #post = "/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Topics"
    url = "/tag/"
    weight = 2    

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/content/page/about/"
    weight = 4
